### PR TITLE
feat: add check to throw if http status is not 200

### PR DESCRIPTION
**Pull request by jacktuck**

### CODE REVIEW

**Comment by jacktuck** [comment]
thanks @davidhq

**Comment by jacktuck** [comment]
Annoyingly semantic release hasn't done a major release there but i think it should have done :(

**Comment by davidhq** [comment]
Nice, I see `if (res.status !== 200) {`, I thought this is better too but you said throw when 4xx or 5xx ... anyhow: great.

**Comment by jacktuck** [comment]
Yep that's my bad, hadn't thought about it in any depth before looking at your branch.

**Pull request merged**
