### PR TITLE
feat: add article type

### PR DESCRIPTION
**Pull request by fuji44**
Please see the issue for the history.
- #80 

I have a few concerns, so please give me some feedback.

- Do not check for og:type.
    - If you want to be fully compliant with the OGP specification, you have to make it work only for `<meta property="og:type" content="article" />`. However, this implementation will always read `article:*`.
- Is the structure of Metadata good?
    - Added under the root instead of under `open_graph` to match the structure of the property names.
- Is the test code in a good place?

### CODE REVIEW

**Comment by jacktuck** [comment]
Thanks for your contribution. 

> Do not check for og:type.
> If you want to be fully compliant with the OGP specification, you have to make it work only for <meta property="og:type" content="article" />. However, this implementation will always read article:*.

I see. I think this is fine for now and we can revisit this in the future if we need to be stricter.

> Is the structure of Metadata good?
> Added under the root instead of under open_graph to match the structure of the property names.

I see why you did that but think  having it under `open_graph` would be more intuitive. I don't mind having a disparity between the structure and property names.

Is the test code in a good place?
Tests look great , nice work! 

I want to revisit the testing approach at some point and look at removing nock and the http server.

**Comment by fuji44** [comment]
> I should revisit the testing approach at some point and look at removing nock and the http server.

I'm not trying to be argumentative here, but can you briefly explain why?

**Comment by fuji44** [comment]
Modified article to be part of open_graph.

**Comment by jacktuck** [comment]
> > I should revisit the testing approach at some point and look at removing nock and the http server.
> 
> I'm not trying to be argumentative here, but can you briefly explain why?

I've not thought about it in any great deal but the current testing approach feels a bit cumbersome.

**Review by jacktuck — APPROVED** [review]

**Pull request merged**
